create table "public"."silence_chunks" (
    "id" bigint generated by default as identity not null,
    "timestamp" timestamp with time zone not null,
    "device_id" text
);


alter table "public"."silence_chunks" enable row level security;

CREATE INDEX idx_silence_chunks_device_id ON public.silence_chunks USING btree (device_id);

CREATE INDEX idx_silence_chunks_device_timestamp ON public.silence_chunks USING btree (device_id, "timestamp");

CREATE INDEX idx_silence_chunks_timestamp ON public.silence_chunks USING btree ("timestamp");

CREATE UNIQUE INDEX silence_chunks_pkey ON public.silence_chunks USING btree (id);

alter table "public"."silence_chunks" add constraint "silence_chunks_pkey" PRIMARY KEY using index "silence_chunks_pkey";

alter table "public"."silence_chunks" add constraint "silence_chunks_device_id_fkey" FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE not valid;

alter table "public"."silence_chunks" validate constraint "silence_chunks_device_id_fkey";

grant delete on table "public"."silence_chunks" to "anon";

grant insert on table "public"."silence_chunks" to "anon";

grant references on table "public"."silence_chunks" to "anon";

grant select on table "public"."silence_chunks" to "anon";

grant trigger on table "public"."silence_chunks" to "anon";

grant truncate on table "public"."silence_chunks" to "anon";

grant update on table "public"."silence_chunks" to "anon";

grant delete on table "public"."silence_chunks" to "authenticated";

grant insert on table "public"."silence_chunks" to "authenticated";

grant references on table "public"."silence_chunks" to "authenticated";

grant select on table "public"."silence_chunks" to "authenticated";

grant trigger on table "public"."silence_chunks" to "authenticated";

grant truncate on table "public"."silence_chunks" to "authenticated";

grant update on table "public"."silence_chunks" to "authenticated";

grant delete on table "public"."silence_chunks" to "service_role";

grant insert on table "public"."silence_chunks" to "service_role";

grant references on table "public"."silence_chunks" to "service_role";

grant select on table "public"."silence_chunks" to "service_role";

grant trigger on table "public"."silence_chunks" to "service_role";

grant truncate on table "public"."silence_chunks" to "service_role";

grant update on table "public"."silence_chunks" to "service_role";


